{
  "id": "test-elasticsearch",
  "description": "Installs Elasticsearch and tests it",
  "run": {
    "cpus": 0.5,
    "mem": 100,
    "disk": 0,
    "artifacts": [
      {
        "uri": "https://raw.githubusercontent.com/dcos/examples/master/1.8/test-suite/install-elasticsearch.sh",
        "executable": true,
        "extract": false,
        "cache": false
      }
    ],
    "cmd": "./install-elasticsearch.sh",
    "env": {
      "DCOS_URL": "http://dcos-exam-elasticl-1oslvib1dxn55-726953633.eu-west-1.elb.amazonaws.com/",
      "DCOS_TOKEN": "eyJhbGciOiJIUzI1NiIsImtpZCI6InNlY3JldCIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIzeUY1VE9TemRsSTQ1UTF4c3B4emVvR0JlOWZOeG05bSIsImVtYWlsIjoibWljaGFlbC5oYXVzZW5ibGFzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJleHAiOjEuNDc4OTU2Mjc2ZSswOSwiaWF0IjoxLjQ3ODUyNDI3NmUrMDksImlzcyI6Imh0dHBzOi8vZGNvcy5hdXRoMC5jb20vIiwic3ViIjoiZ2l0aHVifDUyNTk0IiwidWlkIjoibWljaGFlbC5oYXVzZW5ibGFzQGdtYWlsLmNvbSJ9.k-vSoPnN3lgPJsgHk-VoCg4bBYqmSzsRJEnngTtGeVg"
    },
    "restart": {
      "policy": "NEVER"
    }
  }
}
